PreCommit:
  Scalastyle:
    enabled: true
    flags: ['-w', 'true', '-c', './project/scalastyle_config.xml', 'src']

  TravisLint:
    enabled: true

  XmlSyntax:
    enabled: true

  YamlSyntax:
    enabled: true