# Changes relative to https://github.com/sds/overcommit/blob/master/config/default.yml
PreCommit:
  Scalastyle:
    enabled: true
    flags: ['-w', 'true', '-c', './project/scalastyle_config.xml', 'src']

  TravisLint:
    enabled: true

  XmlSyntax:
    enabled: true

  YamlSyntax:
    enabled: true