PreCommit:
  Scalastyle:
    enabled: true
    flags: ['-c', 'project/scalastyle-config.xml', 'src/main/scala']

  TravisLint:
    enabled: true

  XmlSyntax:
    enabled: true

  YamlSyntax:
    enabled: true